name = "PrimeCert"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["PrimeCert"]
testDriver = "PrimeCertTest"

[leanOptions]
pp.unicode.fun = true # pretty-prints `fun a ↦ b`
autoImplicit = false
relaxedAutoImplicit = false
weak.linter.mathlibStandardSet = true
maxSynthPendingDepth = 3

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "571b8a8e54219b4d393f75f4b8653fac08197fcc"

[[lean_lib]]
name = "PrimeCert"

[[lean_lib]]
name = "PrimeCertTest"
globs = ["PrimeCertTest.+"]
