name = "PrimeCert"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["PrimeCert"]
testDriver = "PrimeCertTest"

[leanOptions]
pp.unicode.fun = true # pretty-prints `fun a ↦ b`
autoImplicit = false
relaxedAutoImplicit = false
weak.linter.mathlibStandardSet = true
maxSynthPendingDepth = 3

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "bb482f116bc7c0dbc55f1eb2d0903e8f6d270462"

[[lean_lib]]
name = "PrimeCert"

[[lean_lib]]
name = "PrimeCertTest"
globs = ["PrimeCertTest.+"]
