name = "PrimeCert"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["PrimeCert"]
testDriver = "PrimeCertTest"

[leanOptions]
pp.unicode.fun = true # pretty-prints `fun a ↦ b`
autoImplicit = false
relaxedAutoImplicit = false
weak.linter.mathlibStandardSet = true
maxSynthPendingDepth = 3

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "06e4a530c2ee8e5c0fc6ba40a38d4814102c8fa2"

[[lean_lib]]
name = "PrimeCert"

[[lean_lib]]
name = "PrimeCertTest"
globs = ["PrimeCertTest.+"]
