"""Write the parts of one half of a record attempt for the sum of 1/p.

Usage: genHigher.py FORM OUTDIR NAMESPACE A0 FILES SEGS

Each part sums `SEGS` segments of 1048576 wheel positions with the given emitter form; a wheel
position covers three integers, so a part spans SEGS*1048576*3 integers and the whole set spans
FILES times that. The two halves of the attempt are generated by two calls with different starts,
so that each half is one job well inside the six hour limit and the two run side by side.
"""

import sys
from pathlib import Path

SCALE = 20
BATCH = 2048
LEN = 1536

FORM = int(sys.argv[1])
OUT = Path(sys.argv[2])
NS = sys.argv[3]
A0 = int(sys.argv[4])
FILES = int(sys.argv[5])
SEGS = int(sys.argv[6])
WIDTH = int(sys.argv[7]) if len(sys.argv) > 7 else 1048576
BOUND = int(sys.argv[8]) if len(sys.argv) > 8 else 110017

RAMP = len(sys.argv) > 9 and sys.argv[9] == "ramp"

# Four files build at a time and they are identical, so their peaks coincide: the record half's
# 13.41 GB was four times one file's. Starting them a quarter of a file apart measured 5.76 GB
# against 7.19 for four together. Giving the first four a quarter, a half, three quarters and a
# whole file of segments staggers the pipeline with no scheduling trick, since each file that
# finishes starts the next immediately and the offsets then persist for the rest of the run.
if RAMP and FILES > 4:
    COUNTS = [max(1, SEGS * k // 4) for k in (1, 2, 3, 4)] + [SEGS] * (FILES - 4)
else:
    COUNTS = [SEGS] * FILES

STARTS = []
acc = A0
for c in COUNTS:
    STARTS.append(acc)
    acc += c * WIDTH * 3
TOP = acc

HEADER = """/-
Copyright (c) 2026 Bhavik Mehta. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Bhavik Mehta
-/
module

"""

assert TOP < BOUND * BOUND, (TOP, BOUND * BOUND)
assert 7 * BOUND <= A0
assert BOUND % 6 in (1, 5)
assert A0 % 6 in (1, 5)

OUT.mkdir(parents=True, exist_ok=True)

for i, (start, segs) in enumerate(zip(STARTS, COUNTS)):
    body = HEADER + f"""public meta import PrimeCert.Meta.PrimeHarmonic
public meta import PrimeCert.SegmentedSieve

/-! # The primes from `{start}`, part {i + 1} of {FILES}

{segs} segments of {WIDTH} wheel positions, sieved by the primes up to `{BOUND}` and summed at
scale `10 ^ {SCALE}` by walking the gaps between the survivors. This set of {FILES} parts carries
`{A0}` to `{TOP - 1}`; `{NS}.All` joins them. The first four parts hold a quarter, a half, three
quarters and a whole file of segments so that four building at once finish at different times and
their peaks stop coinciding.
-/

namespace PrimeCert.{NS}.P{i:02d}

set_option maxRecDepth 4000000 in
set_option Elab.async false in
run_harmonic_series {start} {WIDTH} {BOUND} {SCALE} {BATCH} {LEN} {segs} {FORM}

end PrimeCert.{NS}.P{i:02d}
"""
    (OUT / f"Part{i:02d}.lean").write_text(body)

imports = "\n".join(f"public import PrimeCertTest.{NS}.Part{i:02d}" for i in range(FILES))
allbody = HEADER + f"""public meta import PrimeCert.Meta.PrimeHarmonic
{imports}

/-! # The primes from `{A0}` to `{TOP - 1}`, in one enclosure

The {FILES} parts sum {sum(COUNTS)} segments of {WIDTH} wheel positions between them; this joins
all of them into one enclosure of the sum of the reciprocals of the primes above `{A0 - 1}` and
below `{TOP}`.
-/

set_option maxRecDepth 4000000 in
set_option Elab.async false in
run_harmonic_join {A0} {WIDTH} {BOUND} {SCALE} {sum(COUNTS)}
"""
(OUT / "All.lean").write_text(allbody)

print(f"{NS}: {FILES} parts, {sum(COUNTS)} segments, form {FORM}, ramp {RAMP}")
print(f"  counts {COUNTS[:6]}{' …' if FILES > 6 else ''}")
print(f"  covers {A0} to {TOP - 1}, {TOP - A0} integers, {sum(COUNTS) * WIDTH} positions")
print(f"  next start {TOP}, {TOP % 6} mod 6")
